# Generated by Django 3.2.3 on 2021-05-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='heroes',
            new_name='characters',
        ),
    ]
