# Generated by Django 3.2.3 on 2021-05-23 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_heroes_article_characters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='characters',
            field=models.TextField(error_messages={'invalid': 'Введите в формате: "<имя> (<год_рождения>-<год_смерти>)"'}, validators=[django.core.validators.RegexValidator(regex='(.+\\s{1}\\(\\d{4}\\-(?:\\d{4}|\\d{0})\\)(\\,\\s)?)+')], verbose_name='Упоминаются'),
        ),
    ]
