# Generated by Django 3.2.3 on 2021-05-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210523_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='caption',
            field=models.CharField(max_length=200, null=True, verbose_name='Подпись'),
        ),
    ]
